version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  exporter:
    build:
      context: ..
      dockerfile: Dockerfile.exporter
    ports: ["9108:9108"]
    depends_on: [redis]

  worker-coder:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_URL: "redis://redis:6379/0"
      AR_ENABLE_METRICS: "1"
      ARX_WORKER_QUEUE: "q.coder"
      ARX_WORKER_CONCURRENCY: "4"
    depends_on: [redis]

  worker-auditor:
    build:
      context: ..
      dockerfile: Dockerfile.worker
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_URL: "redis://redis:6379/0"
      AR_ENABLE_METRICS: "1"
      ARX_WORKER_QUEUE: "q.auditor"
      ARX_WORKER_CONCURRENCY: "2"
    depends_on: [redis]

