name: Validate AdvancedRules

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project + CLI (editable)
        run: |
          pip install -e .
          pip install prometheus-client celery redis

      - name: Sanity: arx CLI present
        run: which arx && arx version

      - name: Run validation suite
        env:
          AR_ENABLE_METRICS: '1'
        run: bash scripts/validate_all.sh
